### PR TITLE
binance fiat data pull and tests

### PR DESCRIPTION
**Pull request by Larision**
Fiat deposit/withrawal pulling correctly as i noticed in #179

### CODE REVIEW

**Comment by macanudo527** [comment]
Thanks for working on this! I can't test it in the real world since I don't work with fiat deposits for Binance.com

Are you able to see all of your missing fiat orders?

**Comment by Larision** [comment]
im seeing all fiat orders, but doing some more checks on it. can you help me a bit with #164 im getting error every time i run dali.
Thanks

**Comment by Larision** [comment]
```
2023-06-03 17:09:40,771/Binance.com/fran/DEBUG: Fiat Order (buy): {"orderNo": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "fiatCurrency": "EUR", "indicatedAmount": "265.00", "amount": "260.23", "totalFee": "4.77", "method": "Card", "status": "Successful", "createTime": "1666799128000", "updateTime": "1666799168000"}
2023-06-03 17:09:40,772/Binance.com/fran/DEBUG: Fiat Order (buy): {"orderNo": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "fiatCurrency": "EUR", "indicatedAmount": "15.00", "amount": "14.73", "totalFee": "0.27", "method": "Card", "status": "Successful", "createTime": "1658668601000", "updateTime": "1658668609000"}
2023-06-03 17:09:40,772/Binance.com/fran/DEBUG: Fiat Order (buy): {"orderNo": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "fiatCurrency": "EUR", "indicatedAmount": "48.00", "amount": "47.14", "totalFee": "0.86", "method": "Card", "status": "Successful", "createTime": "1658668464000", "updateTime": "1658668470000"}
2023-06-03 17:09:40,772/Binance.com/fran/DEBUG: Fiat Order (buy): {"orderNo": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "fiatCurrency": "EUR", "indicatedAmount": "25.00", "amount": "24.55", "totalFee": "0.45", "method": "Card", "status": "Successful", "createTime": "1654367531000", "updateTime": "1654367537000"}
2023-06-03 17:09:40,772/Binance.com/fran/DEBUG: Fiat Order (buy): {"orderNo": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "fiatCurrency": "EUR", "indicatedAmount": "50.00", "amount": "49.10", "totalFee": "0.9", "method": "Card", "status": "Successful", "createTime": "1651513872000", "updateTime": "1651513877000"}
2023-06-03 17:09:40,773/Binance.com/fran/DEBUG: Fiat Order (buy): {"orderNo": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "fiatCurrency": "EUR", "indicatedAmount": "400.00", "amount": "392.80", "totalFee": "7.2", "method": "Card", "status": "Successful", "createTime": "1647360124000", "updateTime": "1647360194000"}
2023-06-03 17:09:40,773/Binance.com/fran/DEBUG: Fiat Order (buy): {"orderNo": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "fiatCurrency": "EUR", "indicatedAmount": "500.00", "amount": "491.00", "totalFee": "9", "method": "Card", "status": "Successful", "createTime": "1638567801000", "updateTime": "1638567827000"}
2023-06-03 17:09:40,773/Binance.com/fran/DEBUG: Fiat Order (buy): {"orderNo": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "fiatCurrency": "EUR", "indicatedAmount": "500.00", "amount": "491.00", "totalFee": "9", "method": "Card", "status": "Successful", "createTime": "1638567509000", "updateTime": "1638567607000"}
2023-06-03 17:09:40,773/Binance.com/fran/DEBUG: Fiat Order (buy): {"orderNo": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "fiatCurrency": "EUR", "indicatedAmount": "500.00", "amount": "491.00", "totalFee": "9", "method": "Card", "status": "Failed", "createTime": "1638556020000", "updateTime": "1638556045000"}

```

Working.

**Review by macanudo527 — APPROVED** [review]
Thanks again, this is obviously an important part of the plugin!

LGTM!

**Pull request merged**
