### PR TITLE
spanish support

### PR DESCRIPTION
**Pull request by Larision**
Here again.
i´m doing separate PR to this and Binance dividends

### CODE REVIEW

**Review by macanudo527 — CHANGES_REQUESTED** [review]
This looks good, just need @eprbell to roll through the changes with rp2.

**Review by eprbell — APPROVED** [review]
I'm back from vacation: thanks for your patience!

**Comment by eprbell** [comment]
I'll publish a new version of RP2 later today: that should solve the static analysis problem.

**Comment by eprbell** [comment]
I published the new RP2 with Spanish support and now this is passing. Ready to merge!

**Review by eprbell — APPROVED** [review]

**Pull request merged**
