### PR TITLE
Reorganize pair converter code

### PR DESCRIPTION
**Pull request by eprbell**
This is preparatory work for my experiments writing a CCXT-based version of the Coinbase plugin (which has been broken by Coinbase, as described in #216).

This PR moves graph/optimization code from abstract_pair_converter_plugin.py to abstract_ccxt_input_plugin.py (no functional change). This is because:
- the code was interfering with simple plugins like Historic-Crypto, which was printing the following message: "No Fiat Access Key. Fiat pricing will NOT be available. To enable fiat pricing, an access key from exchangerate.host is required.". This was confusing because Historic-Crypto has no dependency on exchangerate.host.
- it's cleaner to have a bare bone top class (abstract_pair_converter_plugin.py) and a graph/optimization-aware subclass (abstract_ccxt_input_plugin.py). This way, simple plugins don't have to inherit the extra complexity of optimization.

This PR also contains minor changes to exception handling: ExchangeError doesn't need to retry.

### CODE REVIEW

**Comment by macanudo527** [comment]
@eprbell Sorry, I did see this. I just need to patch code to see if it works. (Right now I can't get accurate prices because things are out of date).

I had to update the fiat pricing and kraken pricing. I think I have it now. I'm going to do some cleaning and submit it. I might need to skip writing tests for now, though. Trying to get it all done before the tax deadline.

**Comment by eprbell** [comment]
> @eprbell Sorry, I did see this. I just need to patch code to see if it works. (Right now I can't get accurate prices because things are out of date).
> 
> I had to update the fiat pricing and kraken pricing. I think I have it now. I'm going to do some cleaning and submit it. I might need to skip writing tests for now, though. Trying to get it all done before the tax deadline.

No worries! Thanks for reviewing my PR: it's good to turn things around :-)

**Comment by macanudo527** [comment]
@eprbell did you mean to create a separate cache for CCXT and the abstract pair plugin? in CCXT there is `self._cache`, but the abstract has `self.__cache`

**Comment by eprbell** [comment]
> @eprbell did you mean to create a separate cache for CCXT and the abstract pair plugin? in CCXT there is `self._cache`, but the abstract has `self.__cache`

I think the `_cache` property should probably be in the top abstract class (i.e. `abstract_pair_converter_plugin.py`) and be inherited by all subclasses including CCXT-based ones.

**Comment by macanudo527** [comment]
> I think the `_cache` property should probably be in the top abstract class (i.e. `abstract_pair_converter_plugin.py`) and be inherited by all subclasses including CCXT-based ones.

OK, that's what I was thinking. I'll fix my code in #225 to reflect that.

**Comment by macanudo527** [comment]
@eprbell This should finally be ready to go. I had to patch the code a little to fix mypy issues https://github.com/eprbell/dali-rp2/pull/218/commits/93018c4824e9244bd59d1fcb6c3abbda11870779 Let me know your thoughts.

**Comment by eprbell** [comment]
> @eprbell This should finally be ready to go. I had to patch the code a little to fix mypy issues [93018c4](https://github.com/eprbell/dali-rp2/commit/93018c4824e9244bd59d1fcb6c3abbda11870779) Let me know your thoughts.

This looks good to me! I can't approve it though, since it's my PR.

**Comment by macanudo527** [comment]
> This looks good to me! I can't approve it though, since it's my PR.

Right. Lol

**Review by macanudo527 — APPROVED** [review]
LGTM!

**Pull request merged**
