### PR TITLE
Update Pionex plugin documentation based on current Pionex transaction download behavior.

### PR DESCRIPTION
**Pull request by kiates**
While working with the Pionex plug-in, it seems that the workflow has changed.  When you download Pionex transactions it provides a zip file with the following files:

- deposit-withdraw.csv
- dust-collector.csv
- for-cointracker.csv
- staking.csv
- structured-products.csv
- trading.csv

I'm guessing that the files other than for_cointracker.csv, and deposit-withraw.csv are not yet supported by the plugin.

### CODE REVIEW

**Comment by macanudo527** [comment]
That is exactly right. I haven't used those features, so I didn't implement them. They do have a REST API now, so I hope I or somebody adds that to CCXT and then life would be easier.

Maybe some day.

**Comment by macanudo527** [comment]
Maybe you could close this, and just keep #139 since you have this commit on that branch?

**Comment by kiates** [comment]
Rebased the other branch to separate it out.

**Comment by eprbell** [comment]
@macanudo527, is it OK to merge this?

**Comment by macanudo527** [comment]
Yes, sorry for the late reply.

**Review by eprbell — APPROVED** [review]

**Pull request merged**
